# Generated by Django 5.2.12 on 2026-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('document', models.FileField(blank=True, null=True, upload_to='notices/', verbose_name='ফাইল/ছবি')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='প্রকাশের সময়')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'নোটিশ',
                'verbose_name_plural': 'নোটিশসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
