# Generated by Django 5.2.12 on 2026-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='ভর্তি চলছে - নাযেরা বিভাগ ও হিফয বিভাগে ভর্তি চলছে', max_length=255, verbose_name='হেডলাইন')),
                ('subheadline', models.CharField(blank=True, max_length=255, verbose_name='সাব-হেডলাইন')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট')),
            ],
            options={
                'verbose_name': 'ভর্তি বিজ্ঞাপন',
                'verbose_name_plural': 'ভর্তি বিজ্ঞাপনসমূহ',
                'ordering': ['-updated_at'],
            },
        ),
    ]
