# Generated by Django 5.2.12 on 2026-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ (টাকা)')),
                ('transaction_type', models.CharField(choices=[('income', 'আয়'), ('expense', 'ব্যয়')], max_length=10, verbose_name='ধরন')),
                ('date', models.DateField(auto_now_add=True, verbose_name='তারিখ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='বিস্তারিত')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='রসিদ')),
            ],
            options={
                'verbose_name': 'লেনদেন',
                'verbose_name_plural': 'লেনদেনসমূহ',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
