# Generated by Django 5.2.12 on 2026-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('boarding', 'বোর্ডিং'), ('student_fees', 'স্টুডেন্ট ফি'), ('admission_fees', 'ভর্তি ফি'), ('salary', 'বেতন'), ('furniture', 'ফার্নিচার'), ('bills', 'বিল'), ('maintenance', 'রক্ষণাবেক্ষণ'), ('others', 'অন্যান্য')], default='others', max_length=20, verbose_name='ক্যাটাগরি'),
        ),
    ]
