# Generated by Django 5.2.12 on 2026-04-02 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='শিক্ষার্থীর নাম')),
                ('roll_no', models.CharField(max_length=20, unique=True, verbose_name='রোল নম্বর')),
                ('class_name', models.CharField(max_length=50, verbose_name='শ্রেণী')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='অভিভাবকের মোবাইল')),
                ('is_active', models.BooleanField(default=True, verbose_name='অধ্যয়নরত')),
            ],
            options={
                'verbose_name': 'শিক্ষার্থী',
                'verbose_name_plural': 'শিক্ষার্থীবৃন্দ',
                'ordering': ['class_name', 'roll_no'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='নাম')),
                ('phone', models.CharField(max_length=20, verbose_name='মোবাইল নম্বর')),
                ('subject', models.CharField(max_length=100, verbose_name='বিষয়')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ইউজার')),
            ],
            options={
                'verbose_name': 'শিক্ষক',
                'verbose_name_plural': 'শিক্ষকবৃন্দ',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='তারিখ')),
                ('is_present', models.BooleanField(default=False, verbose_name='উপস্থিত')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='শিক্ষার্থী')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.teacher', verbose_name='শিক্ষক')),
            ],
            options={
                'verbose_name': 'উপস্থিতি',
                'verbose_name_plural': 'উপস্থিতি রেকর্ড',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
