# Generated by Django 5.2.12 on 2026-04-02 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('nazera', 'নাযেরা বিভাগ'), ('hifz', 'হিফয বিভাগ')], max_length=20, verbose_name='বিভাগ')),
                ('guardian_name', models.CharField(max_length=150, verbose_name='অভিভাবকের নাম')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('admission_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ভর্তি ফি (টাকা)')),
                ('paid_in_cash', models.BooleanField(default=True, verbose_name='ক্যাশে পরিশোধ')),
                ('admitted_by_signature', models.CharField(max_length=150, verbose_name='শিক্ষকের স্বাক্ষর (নাম)')),
                ('remarks', models.TextField(blank=True, verbose_name='মন্তব্য')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ভর্তির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট')),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.teacher', verbose_name='ভর্তি কার্যক্রম পরিচালনাকারী শিক্ষক')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_record', to='academic.student', verbose_name='শিক্ষার্থী')),
            ],
            options={
                'verbose_name': 'ভর্তি রেকর্ড',
                'verbose_name_plural': 'ভর্তি রেকর্ডসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
