# Generated by Django 5.2.12 on 2026-04-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_admissionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrecord',
            name='section',
            field=models.CharField(choices=[('nazera', 'নাযেরা বিভাগ'), ('hifz', 'হিফয বিভাগ'), ('class_1', 'প্রথম শ্রেণী'), ('class_2', 'দ্বিতীয় শ্রেণী'), ('class_3', 'তৃতীয় শ্রেণী'), ('class_4', 'চতুর্থ শ্রেণী'), ('class_5', 'পঞ্চম শ্রেণী'), ('class_6', 'ষষ্ঠ শ্রেণী'), ('class_7', 'সপ্তম শ্রেণী'), ('class_8', 'অষ্টম শ্রেণী'), ('class_9', 'নবম শ্রেণী'), ('class_10', 'দশম শ্রেণী')], max_length=20, verbose_name='বিভাগ'),
        ),
    ]
