# Generated by Django 5.2.12 on 2026-04-02 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_admissionrecord_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add_student', 'শিক্ষার্থী যুক্ত'), ('remove_student', 'শিক্ষার্থী মুছে ফেলা'), ('attendance', 'উপস্থিতি নেওয়া')], max_length=20, verbose_name='কার্যক্রম')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='শ্রেণী')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='বিস্তারিত')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='সময়')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.student', verbose_name='শিক্ষার্থী')),
            ],
            options={
                'verbose_name': 'শিক্ষক কার্যক্রম',
                'verbose_name_plural': 'শিক্ষক কার্যক্রমসমূহ',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
